name: jupyter_docx_bundler

channels:
  - defaults
  - conda-forge
  - mrossi

dependencies:
  - matplotlib
  - nbconvert >=5.3.1
  - nbformat
  - notebook >=5.0
  - numpy
  - pillow
  - pypandoc >=1.4
  - pytest
  - python >=3.6
  - requests
