name: jupyter_docx_bundler
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - nbconvert >=5.3.1
  - nbformat
  - notebook >=5.0
  - numpy
  - pandoc
  - pillow
  - pypandoc >=1.4
  - pytest
  - pytest-azurepipelines >=0.6.0
  - pytest-cov
  - python >=3.6
  - requests
