package:
  name: jupyter_docx_bundler
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
  run:
    - python
    - notebook >=5.0
    - pypandoc >=1.4
    - nbconvert >=5.3.1
    - pandoc >=1.19.2.1

about:
  home: https://github.com/m-rossi/jupyter_docx_bundler
  license: MIT
  license_file: LICENSE
  summary: Jupyter bundler extension to export notebook as a docx file
