{% if GIT_DESCRIBE_NUMBER == '0' %}
{% set version = GIT_DESCRIBE_TAG %}
{% else %}
{% set version = GIT_DESCRIBE_TAG + '.dev' + GIT_DESCRIBE_NUMBER %}
{% endif %}
package:
  name: jupyter-docx-bundler
  version: {{version}}

source:
  path: ..

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools >=38.6.0
    - setuptools_scm
  run:
    - python
    - notebook >=5.0
    - pypandoc >=1.4
    - nbconvert >=5.3.1
    - pandoc

test:
  imports:
    - jupyter_docx_bundler
  requires:
    - matplotlib
    - nbformat
    - pillow
    - pytest
    - pytest-azurepipelines >=0.6.0
    - pytest-cov
    - requests
  commands:
    - pytest --pyargs jupyter_docx_bundler

about:
  home: https://github.com/m-rossi/jupyter-docx-bundler
  license: MIT
  license_file: LICENSE
  summary: Jupyter bundler extension to export notebook as a docx file
