package:
  name: jupyter_docx_bundler
  version: 0.1.1

source:
  path: ..

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - jupyter
    - notebook >=5.0
    - pypandoc >=1.4
    - nbconvert >=5.3.1
    - pandoc >=1.19.2.1

about:
  home: https://github.com/m-rossi/jupyter_docx_bundler
  summary: Jupyter bundler extension to export notebook as a docx file
