name: "Continous integration"

on: push

jobs:
  flake8:
    name: flake8
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: 3.8
          activate-environment: flake8
      - name: Install dependencies
        shell: bash -l {0}
        run: conda install --yes --quiet flake8
      - name: Execute flake8
        shell: bash -l {0}
        run: flake8 . --max-line-length=99

  pytest:
    needs: flake8
    name: pytest (Python ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.6', '3.7', '3.8']
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: test
      - name: Add conda-forge channel
        shell: bash -l {0}
        run: conda config --append channels conda-forge
      - name: Install dependencies
        shell: bash -l {0}
        run: conda install --yes --quiet --file requirements.txt --file requirements_test.txt
      - name: Execute pytest
        shell: bash -l {0}
        run: pytest . --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

  conda-build:
    needs: pytest
    name: conda-build (Python ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.6', '3.7', '3.8']
    steps:
      - uses: actions/checkout@v2
      - name: Fetch history for all branches and tags
        run: git fetch --prune --unshallow
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
      - name: Install conda-build
        shell: bash -l {0}
        run: conda install --yes --quiet conda-build
      - name: Add conda-forge channel
        shell: bash -l {0}
        run: conda config --append channels conda-forge
      - name: Execute conda-build
        shell: bash -l {0}
        run: conda build --output-folder conda-bld --python ${{ matrix.python-version }} conda.recipe
      - name: Determine files to upload
        id: getfilename
        run: ls conda-bld/*/*.tar.bz2
      - uses: actions/upload-artifact@v1
        with:
          path: ${{ steps.getfilename.outputs.file }}
