name: "Continous integration"

on: push

jobs:
  pep8:
    name: flake8 (${{ matrix.python-version }})
    runs-on: 'ubuntu-latest'
    steps:
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: 3.8
      - name: Install dependencies
        run: conda install --yes --quiet flake8
      - name: Execute flake8
        shell: bash -l {0}
        run: flake8 . --max-line-length=99

  pytest:
    name: pytest (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.6', '3.7', '3.8']
    steps:
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: conda version
        run: conda --version
